Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/centos-stream-9"
   config.vm.network "private_network", ip: "192.168.56.16"
   config.vm.network "public_network"
   config.vm.provision "shell", inline: <<-SHELL
     yum install httpd wget unzip git -y
	 mkdir /opt/devopsdir
	 free -m
	 uptime
   SHELL
end

